---
- name: run apt updates
  become: yes
  apt: 
    update_cache: yes
    upgrade: yes
    autoremove: yes
 
- name: run firmware updates
  become: yes
  expect: 
    cmd: rpi-update
    expect:
      'proceed?':
        - y
  register: _rpi_update
  changed_when: '"reboot needed" in _rpi_update'
  notify: reboot raspi 

- name: add default lines to config.txt
  become: yes
  lineinfile:
    path: /boot/config.txt
    regexp: "{{ item }}"
    line: "{{ item }}"
  with_items: "{{ global.config_txt|default([]) + config_txt }}"
  notify: reboot raspi
...
