---

pirelays_git_url: https://github.com/sandinak/homebridge-pirelays.git
 
node_modules: /usr/local/lib/node_modules

nodejs_apt_packages:
  - nodejs
  - gcc
  - g++
  - make
  - python

# not used by default
nodejs_npm_packages:
  - homebridge-config-ui-x
  - homebridge-http-switch
  - homebridge-http-temperature-sensor
  - homebridge-gpio-services
  - homebridge-ds18b20
  - homebridge-pi-thermostat
...
