#! /bin/sh
### BEGIN INIT INFO
# Provides:          audio_config
# Required-Start:    $all 
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Configure Audio mixer
### END INIT INFO

echo " set audio output to 3.5mm"
/usr/bin/amixer cset numid=3 1

echo " set audio volume to 100% "
amixer sset PCM,0 100%

