---
homebridge_config:
  description: "{{inventory_hostname}} homebridge "
  bridge:
    name: garage
    username: "{{ansible_default_ipv4.macaddress | upper}}"
    port: 51826
    pin: 224-71-001
  accessories:
    # temp sensors
    # https://github.com/dakl/homebridge-pirelays
    # https://www.waveshare.com/wiki/RPi_Relay_Board
    - accessory: homebridge-relays.Switch
      name: Outside Leds
      pin: "37"
    #- accessory: homebridge-pirelays.Switch
    #  name: Outside Leds
    #  pin: "38"
    #- accessory: homebridge-pirelays.Switch
    #  name: Outside Leds
    #  pin: "40"
    
  platforms:  
    - name: Config
      port: 8581
      platform: config

nodejs_npm_packages:
  - homebridge
  - homebridge-config-ui-x
  - homebridge-relays