---

- name: install packages
  become: yes
  apt: 
    state: present
    name: "{{ item }}"
  with_items: "{{ airplay_packages }}"

- include: shairport-sync.yml

- name: set audio char
  become: yes
  copy: 
    src: etc/init.d/audio
    dest: /etc/init.d/audio
    mode: 0755
    owner: root
    group: root
  notify: configure audio

- name: start service shairport-sync
  become: yes
  service:
    name: shairport-sync
    state: started
   
- name: set startup link in /etc/rc2.d
  become: yes
  file: 
    state: link
    src: /etc/init.d/audio
    path: /etc/rc2.d/S02audio

...
