---
- name: verify config has ipv6 disabled.
  assert:
    that: ipv6_disable == True
    msg: ipv6 MUST be disabled for homebridge to work correctly. Update inventory.

- name: install node.js repository
  shell:
    curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -
  args:
    creates: /etc/apt/sources.list.d/nodesource.list

- name: install apt packages {{ nodejs_apt_packages }}
  become: yes
  apt:
    name: "{{ nodejs_apt_packages }}"
  register: node_js_installation 

- name: install/update npm
  become: yes
  npm: 
    name: npm
    global: yes
  when: node_js_installation is changed

# we do NOT use global installs here
# should use ~pi/node_modules/.staging 
- name: install/update homebridge 
  become: yes
  npm:
    state: present
    global: yes
    name: "{{item}}"
    unsafe_perm: yes
  loop: "{{nodejs_npm_packages}}" 

- name: install and configure startup
  become: yes
  shell: /usr/bin/hb-service install --user homebridge
  args:
    creates: /etc/systemd/system/homebridge.service

- name: make setup dir  
  become: yes
  file:
    state: directory
    path: /var/lib/homebridge
    owner: homebridge
    group: homebridge

#- name: install pirelays
#  include_tasks: pirelays.yml

- name: configure homebridge
  become: yes
  tags: config
  template:
    src: "{{item}}.j2"
    dest: "/{{item}}"
    owner: homebridge
    group: homebridge
  with_items:
    - var/lib/homebridge/config.json
  notify: restart homebridge

- name: startup service
  tags: config
  become: yes
  service:
    name: homebridge
    enabled: yes
    state: started

...
 