---
- name: get latest version of pirelays
  become: yes
  git: 
    repo: "{{pirelays_git_url}}"
    dest: "/root/homebridge-pirelays"
    force: yes


- name: build pirelays
  become: yes
  shell: npm install -g --unsafe-perm --no-bin-links homebridge-pirelays
  args:
    chdir: "/root"
    

