---
- name: setup audio config
  tags: audio_config
  block: 
    - name: install audio_config
      become: yes
      copy: 
        src: files/etc/init.d/audio_config
        dest: /etc/init.d/audio_config
      register: _rc_audio_config

    - name: setup audio_config service
      become: yes
      shell: update-rc.d audio_config {{item}}
      with_items:
        - defaults
        - enable
      when: _rc_audio_config is changed

...
