---
- name: base configurationm
  become: yes
  tags: base
  block:
    - name: set hostname to {{inventory_hostname}}
      hostname: 
        name: "{{inventory_hostname}}"

    - name: install base packages
      package: 
        state: present
        name: "{{base.packages}}"
        
    - name: install RedHat Packages
      package: 
        state: present
        name: "{{os_packages.redhat}}"
      when: 
        - os_packages.redhat is defined
        - ansible_os_family == "RedHat"

    - name: remove colorls ( because it sucks ) 
      file: 
        state: absent
        path: /etc/profile.d/{{item}}
      loop: 
        - colorls.sh
        - colorls.csh