---
- name: install squid
  tags: squid
  become: yes
  block: 
    - name: install squid
      package: 
        state: present
        name: squid

    - name: start squid
      service:
        name: squid
        state: started
        enabled: yes