---
- name: configure hosts
  hosts: all
  gather_facts: no
  pre_tasks:
    - block: 
        - ping:

      rescue: 
        - name: set password to default and try again
          set_fact:
            ansible_ssh_pass: "{{raspi_default_password}}" 
          when: raspi_default_password is defined
         
        - ping: 
         
    - name: push key from ~/.ssh/id_rsa.pub
      authorized_key:
        state: present
        user: pi
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  roles: 
    - auth
    - rsyslog

