---
- name: setup raspi config
  hosts: pi-builder
  gather_facts: no
  vars:
    iso_path: /Users/branson/Documents/Images/2019-04-08-raspbian-stretch-lite.img

  pre_tasks:
    - name: check for mount
      changed_when: false
      shell: 
        diskutil list |
        grep -B 4 FAT_32 |
        grep \/dev\/ |
        awk '{ print $1 }'
      register: _diskutil_list
      failed_when: _diskutil_list.stdout_lines | length == 0
      
    - name: extract disk name
      set_fact:
        disk_device_name: "{{ _diskutil_list.stdout.split('/')[-1] }}"
 
    - name: unmount disk
      shell: diskutil unmountDisk {{disk_device_name}}
    
    - name: burn image
      become: yes
      shell: dd 
        if={{iso_path}} 
        of=/dev/r{{disk_device_name}}
        bs=512k
    
    - name: check for mount 
      shell: ls /Volumes/boot
      
    - name: enable ssh
      shell: touch /Volumes/boot/ssh
      
  roles: 
    - role: pi-builder/wifi
