---
fail2ban:
  # jail.conf
  jail_conf: 
    bantime: 3600
    ban_action: iptables-multiport
    findtime: 600
    maxretry: 3

    ignoreips: 
        10.8.0.0/16,
        127.0.0.0/8
        72.84.0.0/15, 
        72.87.0.0/19, 
        72.87.32.0/20, 
        72.74.0.0/15, 
        72.86.0.0/16, 
        72.80.0.0/14, 
        72.73.128.0/17, 
        72.76.0.0/14,
        98.160.0.0/11,
        173.32.0.0/11,
        173.64.0.0/12,
        
  # jails.local
  jails:
    sshd:
      enabled: true
    postfix: 
      enabled: true
      mode: aggressive
      maxretry: 1
    sshd-invaliduser:
      enabled: true
      maxretry: 1
      port: ssh
      logpath: '%(sshd_log)s'
      backend: '%(sshd_backend)s'

    ssh-disconnect:
      enabled: true
      maxretry: 1
      port: ssh,sftp
      filter:  sshd-disconnect
      logpath: /var/log/secure

    ssh-breakin:
      enabled: true
      maxretry: 1
      port: ssh,sftp
      filter: sshd-disconnect
      logpath:  /var/log/secure

    mysqld-auth:
      enabled: true

    apache-nohome:
      enabled: true

    apache-noscript:
      enabled: true

    apache-modsecurity:
      enabled: true

    apache-overflows:
      enabled: true

    apache-badbots:
      enabled: true

    http-get-dos:
      enabled: true

    dovecot: 
      enabled: true
      maxretry: 1
      