---
default_virtual_host: sandsite.org 

virtual_hosts:
  # base site
  sandsite.org:
    aliases: 
      - new.sandsite.org
      - sandsecurity.com
      - shmooconlabs.net
      
    http_conf: 
      ServerAlias: "*.sandsite.org"
      DirectoryIndex: index.html index.php

    document_root_settings:
      Options: FollowSymLinks
      AllowOverride: All
      Require: all granted

  clanmathesonusa.org:
    aliases:
      - clanmathesonusa.com
    http_conf:
      ServerAlias: "*.clanmathesonusa.org"
      ServerAlias: "*.clanmathesonusa.com"
 
  autoblame.com:
    aliases:
      - autoblame.org
    http_conf:
      ServerAlias: "*.autoblame.com"
      ServerAlias: "*.autoblame.org"
      
      
 