---
default_virtual_host: sandsite.org 

virtual_hosts:
  # base site
  sandsite.org:
    aliases: 
      - new.sandsite.org
      - sandsecurity.com
      
    http_conf: 
      ServerAlias: "*.sandsite.org"
      DirectoryIndex: index.html index.php

    document_root_settings:
      Options: FollowSymLinks
      AllowOverride: All
      Require: all granted

  autoblame.com:
    aliases:
      - autoblame.org
    http_conf:
      ServerAlias: "*.autoblame.com"
 
  everblue.fish:
    http_conf:
      ServerAlias: "*.everblue.fish"

#  hwahasterriblecustomerservice.com:
#    http_conf: 
#      ServerAlias: "*.hwahasterriblecustomerservice.com"
#  ansipl.org:
#    http_conf:
#      ServerAlias: "*.ansipl.org"

#  clanmathesonusa.org:
#    aliases:
#      - clanmathesonusa.com
#    http_conf:
#      ServerAlias: "*.clanmathesonusa.org"
 